### PR TITLE
Issue #198 speedup via Numba of entropy.py _match_length()

### PR DESCRIPTION
**Pull request by Gunther-Schulz**
# Description

Improving the processing speed of Entropy Features from issue [#198](https://github.com/hudson-and-thames/mlfinlab/issues/198) by making the function _match_length() compatible with Numba. 
I choose Numba over Cython (as suggested in the issue) for now, would be interesting to compare the performance of both sometime.

Or rewrite __mlfinlab__ in [Julia](https://julialang.org/) :laughing: 

# Test showcase
This diff patches the relevant test to use string message of length * 1000 or demonstration purposes.

```diff
diff --git a/mlfinlab/tests/test_microstructural_features.py b/mlfinlab/tests/test_microstructural_features.py
index e447f315..b93539c6 100644
--- a/mlfinlab/tests/test_microstructural_features.py
+++ b/mlfinlab/tests/test_microstructural_features.py
@@ -136,18 +136,21 @@ class TestMicrostructuralFeatures(unittest.TestCase):
         plug_in_arr = get_plug_in_entropy(message_array, word_length=1)
         lempel = get_lempel_ziv_entropy(message)
         konto = get_konto_entropy(message)
+        konto1000 = get_konto_entropy(message*1000)
 
         self.assertEqual(plug_in, plug_in_arr)
         self.assertAlmostEqual(shannon, 1.0, delta=1e-3)
         self.assertAlmostEqual(lempel, 0.625, delta=1e-3)
         self.assertAlmostEqual(plug_in, 0.985, delta=1e-3)
         self.assertAlmostEqual(konto, 0.9682, delta=1e-3)
+        self.assertAlmostEqual(konto1000, 0.0133, delta=1e-3)
 
         # Konto entropy boundary conditions
         konto_2 = get_konto_entropy(message, 2)
         _match_length('1101111', 2, 3)
         self.assertAlmostEqual(konto_2, 0.8453, delta=1e-4)
-        self.assertEqual(get_konto_entropy('a'), 0)  # one-character message entropy = 0
+        # one-character message entropy = 0
+        self.assertEqual(get_konto_entropy('a'), 0)
 
     def test_encoding_schemes(self):
         """
```

| Native Python | Numba | Test(s) |
|-|-|-|
|  __16.9s__ | __8.6s__ | `python -m unittest test_microstructural_features.TestMicrostructuralFeatures.test_entropy_calculations` |

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] `python -m unittest test_microstructural_features.TestMicrostructuralFeatures.test_entropy_calculations`

**Test Configuration**:
* Manjaro Linux
* VSCode

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by PanPip** [comment]
@Gunther-Schulz  for some reason the Pull Request Build wasn't passing.

Your commit is moved to PR #412 and will soon be merged into develop branch. Thank you! 🙂

**Comment by rspadim** [comment]
these functions could use numpy array instead of strings, it's better to numba, I sent one example to @Jackal08 someday

the idea is instead of a string of chars (unicode chars btw) use an array of numpy uint8, here:

https://github.com/hudson-and-thames/mlfinlab/blob/master/mlfinlab/microstructural_features/entropy.py#L67

if the message is a string, change it to an array of bytes, and after an np.array of uint8, numba like numpy array more than a str object, it can prange and execute for faster

**Comment by rspadim** [comment]
`len(message)` will be `message.shape[0]`

`message not in some_array` will be `not np.isin(message,some_array)`

`message + other string` will include a new item to message np.array, `a = numpy.append(a, new_element)` do the trick "ok" not the fastest way, but it's ok (the fast way is convert an list to np.array if i'm not wrong, but i think it's not friendly to numba, must tcheck)

`msg1 == msg2` can be rewrite to `(msg1 == msg2).all()`

if i didn't forgot, that's all changes that need in entropy.py example

**Comment by rspadim** [comment]
the input could be a list, str, numpy.array, pandas.series

`list` will be converted to `numpy.array`, `pandas.Series` will use `series.values`, `str` will need a `np.array([i for i in str_variable.encode('utf-8')])`

**Comment by PanPip** [comment]
@rspadim that is an interesting idea. Thanks for the guide on how to implement it.

I'll create an issue for this and will try to implement it in the future.

**Pull request closed without merging**
