### PR TITLE
Optimized Images

### PR DESCRIPTION
**Pull request by vardaan-raj**
# Description

I have optimized the images present in this repository by compressing their size without compromising their quality.

Fixes # (Optimization of images)

Compressed the size to better manage the images

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Installed on the local system(using windows) and verified that the product didn't break

### CODE REVIEW

**Comment by Jackal08** [comment]
My primary concern is that the images execute code or contain hidden messages/security threats.

**Comment by vardaan-raj** [comment]
https://github.com/vardaan-raj/mlfinlab/pull/1#issue-721903036

As you can see by visiting the above link, I have used img-bot which is a simple application that optimizes the images using lossless compression. 

I have not changed or altered anything, just compressed the sizes to make the images more space-efficient, without compromising their quality!

**Comment by vardaan-raj** [comment]
Any existing functionality is not changed or broken, just the images have been optimized.

**Comment by Jackal08** [comment]
@vardaan-raj, thank you for putting in the effort but I just can't take the risk, nor do we have the capacity right now to go through it very carefully to do a security audit. 

Right now the risk for this PR far outway the benefit of having a slightly smaller image file.

**Pull request closed without merging**
