### PR TITLE
Ray support for higher multi threading performance

### PR DESCRIPTION
**Pull request by Gunther-Schulz**
# Description

Add support for [Ray](https://github.com/ray-project/ray) to the mlfinalb `multiprocess` module to speed up multi threaded calculations.

When the presence of the [Ray](https://github.com/ray-project/ray)  module is detected, it will be used in place of python `multiprocessing`. Otherwise we fall back to the default `multiprocessing` module.

Running the unit tests vanilla does not show the potential of [Ray](https://github.com/ray-project/ray)  compared to `multiprocessing`, because the performance increase gets offset by the overhead of initializing Ray.

For the purpose of showcasing the potential performance increase I have slightly modified some tests to run 100 times in a loop in an attempt to simulate a higher and closer to real world usage workload.
These modified tests can be found in the following branch:
[ray-support-showcase](https://github.com/Gunther-Schulz/mlfinlab/tree/ray-support-showcase)

To install the branch with pip run:
`pip install git+https://github.com/Gunther-Schulz/mlfinlab@ray-support-showcase`

My results running an Intel(R) Xeon(R) CPU E3-1240 v3 @ 3.40GHz with 32Gb RAM:

| Test(s) | Python SL multiprocessing | Ray |
|-|-|-|
| `python -m unittest test_labels.py test_sample_weights.py test_sampling.py test_sb_bagging.py` |  __418s__ | __193s__ |
| `python -m unittest test_labels.py` |  __148s__ | __47s__ |
| `python -m unittest test_sample_weights.py` |  __144s__ | __47s__ |
| `python -m unittest test_sampling.py` |  __35s__ | __8s__ |
| `python -m unittest test_sb_bagging.py` |  __217s__ | __141s__ |

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] `python -m unittest test_labels.py`
- [x] `python -m unittest test_sample_weights.py`
- [x] `python -m unittest test_sampling.py `
- [x] `python -m unittest test_sb_bagging.py`

**Test Configuration**:
* Manjaro Linux
* VSCode

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] I have added documentation

### CODE REVIEW

**Comment by Gunther-Schulz** [comment]
I am not sure why these commits show up in this PR. Should I resubmit or is this how it should be?

@WanABRO
Update hrp.py
dbcf6b0
@WanABRO
Update test_hrp.py
2688041
@WanABRO
Update hierarchical_risk_parity.rst
b622d92
@WanABRO
Update test_hrp.py
b04337b
@proskurin
Merge branch 'develop' into HRP_custom
0f16868
@WanABRO
Add seriated correlations
0ad0a7b
@WanABRO
define corr matrix before if
46104c2

**Comment by rspadim** [comment]
this is one of best multiprocessing libs i used with python

there's some others wrapping some methods of pandas (pandarel) but if we build from scratch a new code i prefer the use of ray

**Comment by bobcolner** [comment]
any updates on this PR? (looks great!)

**Comment by Jackal08** [comment]
Hi @bobcolner, 

I am very hesitant to add any new dependencies to the library. We already have too many. 

I like this PR. However, there is another priority queue which has our focus. When things free up, we can revisit this. 

Best
Jacques

**Comment by bobcolner** [comment]
Sounds good, thanks for the insight.

Is the priority queue public (can you share) I may be able to contribute.

**Comment by Gunther-Schulz** [comment]
> Hi @bobcolner,
> 
> I am very hesitant to add any new dependencies to the library. We already have too many.
> 
> I like this PR. However, there is another priority queue which has our focus. When things free up, we can revisit this.
> 
> Best
> Jacques

Hi, That is why is a completely optional dependency. The code checks, if the Ray module is installed. If not it falls back to python multiprocessing.

**Pull request closed without merging**
