### PR TITLE
detone() assumes denoised correlation matrix

### PR DESCRIPTION
**Pull request by emoen**
# Description

detone() assumes denoised correlation matrix, so dont denoise correlation(twice)

Also added test of eigenvalue and eigenvector from correlation matrix in detone test.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] python test_risk_estimator

**Test Configuration**:
* Operating system windows 10

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by emoen** [comment]
it doesnt build:https://travis-ci.com/github/hudson-and-thames/mlfinlab/pull_requests but I dont see any build error

**Comment by Jackal08** [comment]
Looks link its failing on the linter. You code doesnt meet PEP8 standards. 

Run the linter locally to check everything passes :)

**Comment by emoen** [comment]
I discovered that num_facts argument to _detoned_corr() isnt being used since the method doesnt denoise the correlation matrix. It should match PEP8 standard.

**Comment by PanPip** [comment]
All looks good, thanks @emoen!

I'll move your commits to mlfinlab branch so that **Travis CI - Branch** build passes.

**Comment by PanPip** [comment]
This PR was moved to PR #426 to pass **Travis CI - Branch** build.

**Pull request closed without merging**
