### PR TITLE
Vpin bug

### PR DESCRIPTION
**Pull request by rspadim**
Divide by rolling window like spec

### CODE REVIEW

**Comment by rspadim** [comment]
Here in brazil there’s a lot of direct cross trading, maybe a good name to volume should be volume_buy_sell instead of only volume, volume=buys+sell+direct cross trading

**Comment by rspadim** [comment]
it's the rolling volume of bars

**Comment by rspadim** [comment]
hi @proskurin 
two points here, the BVC isn't a good function to test, we should get at least a up/down or a buy/sell series, i create a small function just to test:

```python
def get_up_down(df, close='close'):
    up_down_series = df[close].copy()
    up_down_series[:] = 0     # set to zero, some transactions can be direct trades instead of only buy/sell
    last_close, last_up_down = None, None
    for i in df.iterrows():
        up_down = 0
        if last_close is not None:
            if i[1][close] < last_close:
                up_down = -1 
            elif i[1][close] > last_close:
                up_down = 1 
            else:
                up_down=last_up_down
            up_down_series.loc[i[0]] = up_down
        last_close, last_up_down = i[1][close], up_down
    return up_down_series

def get_vpin(volume: pd.Series, buy_volume: pd.Series, window: int = 1) -> pd.Series:
    """
    Get Volume-Synchronized Probability of Informed Trading (VPIN) from bars, p. 292-293.

    :param volume: (pd.Series) bar volume
    :param buy_volume: (pd.Series) bar volume classified as buy (either tick rule, BVC or aggressor side methods applied)
    :param window: (int) estimation window
    :return: (pd.Series) VPIN series
    """
    sell_volume = volume - buy_volume
    return (
        abs((buy_volume-sell_volume).rolling(window=window).sum()) / 
        volume.rolling(window=window).sum()
    )


import pandas as pd
df = pd.read_csv('tests/test_data/dollar_bar_sample.csv', index_col='date_time', parse_dates=[0])
df['up_down'] = get_up_down(df)    # get up/down (up should be buy volume... but we are just testing)

# include direction buy/sell volume
df['buy_sell_volume'] = df['up_down'] * df['cum_vol']
df['buy_volume'] = df['buy_sell_volume']
df.loc[df['buy_volume']<0, 'buy_volume'] = 0


pd.concat([
df['buy_volume'].rolling(window=20).sum().dropna(),  # buy
df['sell_volume'].rolling(window=20).sum().dropna(),  # sell
abs((df['buy_volume']-df['sell_volume']).rolling(window=20).sum().dropna()), # inbalance unsigned
abs((df['buy_volume']-df['sell_volume']).rolling(window=20).sum().dropna())/
df['cum_vol'].rolling(window=20).sum().dropna(), # vpin
df['cum_vol'].rolling(window=20).sum().dropna() # cum vol
], axis=1)
```

**Comment by rspadim** [comment]
i sent another pull request from github website, maybe we could close this one

**Comment by PanPip** [comment]
This PR was moved to #225.

**Pull request closed without merging**
